#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import cv2
import numpy as np
from PIL import Image
#img1=cv2.imread('G:/stego of me/cat 1/cat.1.jpg')
#img2=cv2.imread('G:/stego of me/cat 75/cat.1.jpg')
#img11=cv2.imread('G:/stego of me/cat 1/cat.1.jpg')
#img12=cv2.imread('G:/stego of me/cat 75/cat.1.jpg')
img1=cv2.imread('G:/stego of me/tiger_right/tiger/0/2.jpg')
img2=cv2.imread('G:/stego of me/tiger_right/tiger/1/2.jpg')
#img1_arr=np.array(img1)
#img2_arr=np.array(img2)
#img1=cv2.imread('G:/image_stego_recognize/J-UNIWARD_matlab_v11/J-UNIWARD_matlab/images_cover/1.jpg')
#img2=cv2.imread('G:/image_stego_recognize/J-UNIWARD_matlab_v11/J-UNIWARD_matlab/images_stego/1.jpg')
num=0
#print(img1)
#print(img2)
#print(img2_arr.shape[2])
#img2_arr.shape[i]   求第i维数组大小
#print(img1.shape[0])
for i in range(img1.shape[0]) :
    change = 1
    #print(img1.shape[1])
  #  if img1.height[i]==img2.height[i]:
   #     change=1
    for j in range(img1.shape[1]):
       # if img1.width[j]==img2.width[j]:
       #     change=1
        for k in range(img1.shape[2]):
         #   if img1.channels[k]==img2.channels[k]:
          #      change=1

            if img1[i,j,k]==img2[i,j,k]:
                change=0
    #print(img1_arr[i,j,k])
    #print(img2_arr[i,j,k])
            if change==1: num=num+1


print(num)



